#!/usr/bin/env python

import sys
import fcntl
import signal
import glob
import re
import os
import atexit
from os import popen


def bail_out(msg):
	print msg
        sys.exit(-1)

try:
    xte_pipe = popen("xte", "w")
except IOError:
    bail_out("Unable to open xte pipe")


try:
	menu_pipe = popen("./grabber-menu", "r")
except IOError:
	bail_out("Unable to invoke grabber-menu")
		
for c in menu_pipe.read():
	xte_pipe.write("key " + c + "\n")

